//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCadastro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int Id { get; set; }
        public int CadastroId { get; set; }
        public string Telefone1 { get; set; }
    }
}
